### ISSUE TITLE
Docker Hub wizzy version critically out of date

### ISSUE THREAD

**Issue by r4j4h** [utkarshcmu/wizzy#104]
Using latest wizzy docker image and Grafana 4 I consistently experience that copying rows or panels results in the panel ids staying the same.

Having multiple panel ids causes erratic behavior in Grafana, including:

- Random display dropout
  - Upon dashboard load, once a given panel id loads the other matching panel id's space remains blank. Upon editing it in any way it restores itself, but sometimes to the other panel's configuration. See next issue:
- Editing one panel id modifies the first matching panel id.
  - Copy a row to the end of a chart, appending the copy basically. Edit the bottom appended chart. Save and refresh. Notice the first chart displays the new name.

This can be remedied by Viewing JSON and manually correcting the panel ids. Upon importing the modified JSON the displays behave as expected.

I can understand cases where maintaining the panel id is desired, cross dashboards for example. Perhaps the user should be given the option to maintain or increment them. Or perhaps an easier way to re-number them?

Moving/copying panels requires the row to already exist, but there is no "create empty row" command. Worse, copying panels also exhibits this same behavior, when the row exists, otherwise it encounters an unhandled error at:

```
/usr/local/lib/node_modules/wizzy/src/components.js:150
				var destPanels = srcRows[destRowNumber-1].panels;
```

I am presuming that this was not the case prior to Grafana 4 and regressed at that time, either way I wanted to raise an issue. If I am doing something wrong please don't hesitate to let me know! :)

**Comment by r4j4h** [comment]
This is supposed to be fixed by #86 via 0.5.7. My docker image is using 0.5.0. I will retitle this issue to request upgrading the official docker hub's version with the real latest.

**Comment by r4j4h** [comment]
As an interim fix for others encountering this use negash's fork: [Docker Hub](https://hub.docker.com/r/negash/wizzy/) and [Github](https://github.com/Negashev/wizzy-docker) links.

Running `npm install -g wizzy` in the official container only results in the following error when running `wizzy`:

```
Error: Sync-request requires node version 0.12 or later.  If you need to use it with an older version of node
you can `npm install sync-request@2.2.0`, which was the last version to support older versions of node.
    at doRequest (/usr/local/lib/node_modules/wizzy/node_modules/sync-request/index.js:15:11)
    at /usr/local/lib/node_modules/wizzy/src/remote/grafana/importSrv.js:62:20
    at arrayEach (/usr/local/lib/node_modules/wizzy/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/usr/local/lib/node_modules/wizzy/node_modules/lodash/lodash.js:9359:14)
    at Request.saveHandler [as _callback] (/usr/local/lib/node_modules/wizzy/src/remote/grafana/importSrv.js:59:8)
    at Request.self.callback (/usr/local/lib/node_modules/wizzy/node_modules/request/request.js:188:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/wizzy/node_modules/request/request.js:1171:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wizzy/node_modules/request/request.js:1091:12)
```

**Comment by r4j4h** [comment]
🎉

**Comment by r4j4h** [comment]
Thank you!! :)
