### ISSUE TITLE
wizzy import dashboard throws an exception

### ISSUE THREAD

**Issue by iakovgan** [utkarshcmu/wizzy#106]
wizzy uses relative path to conf file. why not using "~/wizzy.conf" ?

This error is quite missleading: 
```
[igan@grafana]$ wizzy import dashboard

/usr/lib/node_modules/wizzy/src/commands.js:69
                        grafana.import(_.drop(commands));
                                      ^
TypeError: Cannot call method 'import' of undefined
    at Commands.instructions (/usr/lib/node_modules/wizzy/src/commands.js:69:18)
    at Command.listener (/usr/lib/node_modules/wizzy/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:95:17)
    at Command.parseArgs (/usr/lib/node_modules/wizzy/node_modules/commander/index.js:630:12)
    at Command.parse (/usr/lib/node_modules/wizzy/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/lib/node_modules/wizzy/src/index.js:14:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

```

**Comment by vonpupp** [comment]
I am having the same error, any ideas?

**Comment by MetikovVadim** [comment]
You need conf/wizzy.conf located in the working directory. That solves the problem.
