### ISSUE TITLE
 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by bonaime** [utkarshcmu/wizzy#118]
Hi,
I have an error import my dashboards 
```error
wizzy import dashboards
Importing 3 dashboards:
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:618:25)
/Users/bonaime/anaconda/lib/node_modules/wizzy/node_modules/sync-request/index.js:77
    throw new Error(res.stderr.toString());
    ^

Error
    at doRequestWith (/Users/bonaime/anaconda/lib/node_modules/wizzy/node_modules/sync-request/index.js:77:11)
    at doRequest (/Users/bonaime/anaconda/lib/node_modules/wizzy/node_modules/sync-request/index.js:20:10)
    at /Users/bonaime/anaconda/lib/node_modules/wizzy/src/remote/grafana/importSrv.js:62:20
    at arrayEach (/Users/bonaime/anaconda/lib/node_modules/wizzy/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/bonaime/anaconda/lib/node_modules/wizzy/node_modules/lodash/lodash.js:9359:14)
    at Request.saveHandler [as _callback] (/Users/bonaime/anaconda/lib/node_modules/wizzy/src/remote/grafana/importSrv.js:59:8)
    at Request.self.callback (/Users/bonaime/anaconda/lib/node_modules/wizzy/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/bonaime/anaconda/lib/node_modules/wizzy/node_modules/request/request.js:1163:10)
```

my conf file is
```file
{
  "config": {
    "grafana": {
      "url": "http://myserver.url:2212/",
      "username": "admin",
      "password": "password"
    }
  }
}
```
wizzy version is 0.6.0 with macos 10.13.1

Thank you

**Comment by bonaime** [comment]
My problem is linked with npm and/or minimatch...
