### ISSUE TITLE
Wizzy doesn't honor proxy settings

### ISSUE THREAD

**Issue by vialde** [utkarshcmu/wizzy#122]
Hi,

Wizzy doesn't seem to work with grafana that's behind a proxy.  To access my grafana server via cli I need to set http_proxy.  Is there a way to set http_proxy so wizzy with use it?

Cheers, 
`✔ temp directory already exists.
Taking 24 snapshots.
/usr/local/lib/node_modules/wizzy/node_modules/sync-request/index.js:91
    throw err;
    ^

Error: connect ETIMEDOUT 10.225.1.73:443
    at doRequestWith (/usr/local/lib/node_modules/wizzy/node_modules/sync-request/index.js:87:17)
    at doRequest (/usr/local/lib/node_modules/wizzy/node_modules/sync-request/index.js:20:10)
    at ClipSrv.dashboard (/usr/local/lib/node_modules/wizzy/src/remote/grafana/clipSrv.js:35:18)
    at Grafana.clip (/usr/local/lib/node_modules/wizzy/src/remote/grafana.js:345:11)
    at Commands.instructions (/usr/local/lib/node_modules/wizzy/src/commands.js:106:12)
    at Command.listener (/usr/local/lib/node_modules/wizzy/node_modules/commander/index.js:300:8)
    at emitOne (events.js:96:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/wizzy/node_modules/commander/index.js:637:12)
    at Command.parse (/usr/local/lib/node_modules/wizzy/node_modules/commander/index.js:457:21)
caryc:conf/ (master✗) $                                                                                              [15:37:27]
`

**Comment by tuan-phan** [comment]
This one related to 'sync-request' library https://github.com/ForbesLindesay/sync-request/issues/40
I'm not sure they will update it.
