### ISSUE TITLE
import dashboards throws a new exception

### ISSUE THREAD

**Issue by nerdfacerory** [utkarshcmu/wizzy#138]
I'm running `wizzy import dashboards` and i get the following error:

```
Importing 110 dashboards:
/app/src/remote/grafana/importSrv.js:73
    if (options.auth.bearer) {
                    ^

TypeError: Cannot read property 'bearer' of undefined
    at Request.saveHandler [as _callback] (/app/src/remote/grafana/importSrv.js:73:21)
    at Request.self.callback (/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
```

I can import one dashboard at a time. I can list the dashboards. My wizzy setup is all good. 

```
$ wizzy status
✔ conf directory exists.
✔ conf file exists.
✔ .git directory exists.
✔ wizzy setup complete.
```

I'm running the latest code from this repo in a docker container. 
Can you please help me fix this?

**Comment by nerdfacerory** [comment]
Ok, so, i've checked the code and i saw that `bearer` needed an `api_key` that i wasn't using. When i was using wizzy installed with npm or the docker image from docker hub i didn't get this error.

 I went to the Grafana UI, i generated an API Token, saved it and used it in wizzy.json and it worked perfectly! 

I don't know why the import works without the API key when i want to import one dashboard at a time or when i imported 54 dashboards at once using wizzy installed via npm.
